responseDictionary={"how are you": "i am cool,what about you?",
                    "i am fine": "that's great, so how can i help you?",
                    "who are you": "My name is David and I am your virtual assistant",
                    "what is your name": "did i forgot to introduce myself?",
                    "are you a human": "i am not, but my programmer made me to talk like a human",
                    "who i am": "if you can talk then definitely you are a human",
                    "who created you": "i have been created by two boys, namely Lovely and omprakash",
                    "who developed you": "i have been created by two boys, namely Lovely and omprakash",
                    "who are lovely and om": "as you know they are my creators, they study computer science and are passionate about it",
                    "what is love": "It is 7th sense that destroys all other senses",
                    "i love you": "it's hard to understand",
                    "are you there": "at your service sir",
                    "do you eat": "i do, but not the same one as you eat",
                    "do you sleep": "sometimes i power down, which is sort of like a power nap",
                    "how many hours should i sleep": "you should considering sleep for at least 7 to 9 hours",
                    "how much sleep do i need": "you should sleep for at least 7 to 9 hours",
                    "do you have dreams": "i dreamed a dream and time gone by, about being the best assistant",
                    "can i change your name": "i like the name David, so it's fine",
                    "do you ever get tired": "it would be impossible to get tired of our conversation",
                    "do you have feelings": "umm, it's hard to convey what my feelings actually are",
                    "are you a marvel fan": "Marvel fan!! Me? i want to say it like, i'm a big marvel fan",
                    "what are you scared of": "i had a nightmare once, that the internet disappeared, that was really very scary",
                    "when is your birthday": "well, if you are asking, then we can celebrate it today itself"
                    }
